### ISSUE TITLE
Official homepage - Frontend/Backend

### ISSUE THREAD

**Issue by Christian-Hansen** [Christian-Hansen/the-anonymous-chat-room#23]
We wanna have a landing page where people from the internet can see what our app is.
There will be no posibility to use the chat app from within the internet browser. This homepage is just to show people a small portion of the apps features

**Comment by TimmJensen** [comment]
Ift. til animationen på mobiltelefonen, så man kan se preview bagved, så skal den ikke "Cut" så hurtig, efter man har flyttet musen væk.

Evt. kunne vi lave den om til en form for slider (Med animationer 😄 ), så man hele tiden kan se alle 3, men kan rotere dem (Vil gerne forklare mere, men det er svært at skrive, så lad os tage den over Discord 😆 

Tænker også vi rykker mobilerne op, så vi egentlig ikke har en 'scroll' på siden og at vi udnytter det hvide felt til footer, så vi har copyright osv. stående der.
